name: First workflow

on:
    push:
        branches: ["**"]

jobs:
    first-job:
        runs-on: ubuntu-latest

        steps:
            -   name: Console log
                run: echo "Hello, world!"