name: First workflow

on:
    pull_request:
        branches: ["**"]
        types:
            - opened
            - synchronize
            - reopened
            - edited
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            -   name: Console log
                run: echo "Hello, world!"
            -   name: Sleep for 10 secs
                run: |
                  sleep 5
    second-job:
        uses: ./.github/workflows/second.yml
        needs: first-job
