name: check_if_version_updated

on:
    workflow_call:

jobs:
    check_version_updated:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout the PR branch
                uses: actions/checkout@v4
                with:
                    fetch-depth: 2 # Fetches enough history to compare

            -   name: Get current version from package.json
                id: current_version
                run: echo "CURRENT_VERSION=$(jq -r '.version' ./package.json)" >> $GITHUB_ENV

            -   name: Checkout to base branch
                run: |
                    git fetch origin ${{ github.base_ref }} --depth=1
                    git checkout origin/${{ github.base_ref }} package.json

            -   name: Get base branch version from package.json
                id: base_version
                run: echo "BASE_VERSION=$(jq -r '.version' ./package.json)" >> $GITHUB_ENV
    
            -   name: Compare versions
                run: |
                    echo "Current version: $CURRENT_VERSION"
                    echo "Base version: $BASE_VERSION"
                    if [ "$CURRENT_VERSION" == "$BASE_VERSION" ]; then
                        echo "Version has not been updated. Failing workflow."
                        exit 1
                    else
                        echo "Version is different. Proceeding."
                    fi
