name: Third workflow

on:
    pull_request:
        branches:
            - main
        types:
          - closed
    workflow_run:
        workflows: [check_if_version_updated]
        types: [completed]

jobs:
    build:
        # if: ${{ github.event.workflow_run.conclusion=='success' }}
        runs-on: ubuntu-latest
        steps:
            -   name: "After the second workflow"
                run: |
                    echo "After the first workflow HEllo world ${{ github.event.workflow_run.conclusion }}"
